baseurl = "https://harmish.in/"
title = "Harmish Khambhaita"
copyright = "&copy; 2018 Harmish Khambhaita"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Default language to use
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Harmish Khambhaita"
  role = "Post-doctoral Researcher"
  organization = "ENSTA ParisTech"
  organization_url = "https://www.ensta-paristech.fr/en/home/"
  gravatar = false
  avatar = "portrait.jpg"  # in `static/img/` folder
  email = "harmish.khambhaita@ensta-paristech.fr"
  address = "Room R.3.27, ENSTA ParisTech, 828, Boulevard des Maréchaux, 91120 Palaiseau, France"
  phone = "+33 (0)1 81 87 20 39"

  date_format = "Mon, Jan 2, 2006"

  # LaTeX math
  math = false # You can enable it locally on a per page basis

  # Code highlighting with highlight.js
  highlight = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:harmish.khambhaita@ensta-paristech.fr"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/harmishhk/"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/harmishhk"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "//www.researchgate.net/profile/Harmish_Khambhaita"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/harmishhk"

# Navigation Links
[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Recent Works"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
[languages.en]
  languageCode = "en-us"
